### PR TITLE
Basic ODT support

### PR DESCRIPTION
**Pull request by bwanders**
Instigated by #33 this PR adds basic ODT support.

### CODE REVIEW

**Comment by bwanders** [comment]
@LarsGit223: This should get basic ODT support to everyone that wants to use the Strata+ODT combo! Drop me a line if you want to get your hands dirty with advanced features like styling — I'll open a new branch for feature building and testing from my side, so you (and anyone else that wants to help out) can place PRs against that branch.

**Comment by LarsGit223** [comment]
Ok, thanks sounds great.

Regarding styling I do not want to add additional styling in ODT export only. If there are existing styling options/features for XHTML then I would like to adopt them as good as possible to the ODT format. If there aren't any then there is nothing left to do at the moment I guess. If I understood your previous posts right then the spans are only used for JavaScript and not for styling?

**Comment by bwanders** [comment]
Correct. The only styling the Strata plugin does is the for the error display and for the interactive data filtering and sorting. Both of which are irrelevant for the ODT export.

The only "styling" that happens is to align the "Next" and "Previous" links by floating them left and right respectively; but that is such a minimal differences between XHTML and ODT that I do not think it worth the effort to replicate that.

Some users might define custom CSS rules that happen to use the spans and classes emitted by Strata, but as far as I have seen in the wild, this is rarely used. I suggest that we leave it at basic support until there's a few users knocking at the door for more complex styling options.

**Comment by LarsGit223** [comment]
:thumbsup: I agree.

I just released a new maintenance release of the ODT plugin. This also includes all changes affecting/required by the strata plugin.

**Pull request merged**
